# Generated by Django 2.2.28 on 2023-11-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231114_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membres',
            new_name='Membre',
        ),
    ]
